version: '3.9'

services:
  nginx:
    depends_on:
      - wordpress
    build: ./nginx
    ports:
      - '443:443'
    volumes:
      - wordpress-data:/app/wordpress
    restart: on-failure

  wordpress:
    depends_on:
      - mariadb
    build: ./wordpress
    expose:
      - '9000'
    volumes:
      - wordpress-data:/app/wordpress
    restart: on-failure

  mariadb:
    build: ./mariadb
    expose:
      - '3306'
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: on-failure

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/data/wordpress"

  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/data/mariadb"

networks:
  compose-bridge:
    driver: bridge