version: '3.9'

services:
  nginx:
    depends_on:
      - wordpress
    build: ./nginx
    ports:
      - '443:443'
    volumes:
      - wordpress-data:/app/wordpress
    restart: on-failure
    networks:
      - compose-bridge

  wordpress:
    depends_on:
      - mariadb
      - redis
    build: ./wordpress
    expose:
      - '9000'
    volumes:
      - wordpress-data:/app/wordpress
    restart: on-failure
    networks:
      - compose-bridge
    environment:
      - PASSWORD=${PASSWORD}

  mariadb:
    build: ./mariadb
    expose:
      - '3306'
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: on-failure
    networks:
      - compose-bridge
    environment:
      - PASSWORD=${PASSWORD}

  redis:
    build: ./redis
    expose:
      - '6379'
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    networks:
      - compose-bridge

  ftp:
    depends_on:
      - wordpress
    build: ./ftp
    ports:
      - '21:21'
    restart: on-failure
    volumes:
      - wordpress-data:/home/ftpuser/wordpress
    networks:
    - compose-bridge

  adminer:
    depends_on:
      - mariadb
    build: ./adminer
    ports:
      - '4242:80'
    restart: on-failure
    networks:
      - compose-bridge

  web:
    build: ./web
    ports:
      - '5000:5000'
    restart: on-failure
    networks:
      - compose-bridge

  uptime:
    build: ./uptime
    ports:
      - '3001:3001'
    restart: on-failure
    networks:
      - compose-bridge

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/data/wordpress"

  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/data/mariadb"

networks:
  compose-bridge:
    driver: bridge
