version: '3.9'

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./nginx
    ports:
      - '443:443'
    volumes:
      - wordpress-data:/app/wordpress
    restart: on-failure
    networks:
      - compose-bridge

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    build: ./wordpress
    expose:
      - '9000'
    volumes:
      - wordpress-data:/app/wordpress
    restart: on-failure
    environment:
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
    networks:
      - compose-bridge

  mariadb:
    container_name: mariadb
    build: ./mariadb
    expose:
      - '3306'
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    environment:
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}

      - USER_LOGIN=${USER_LOGIN}
      - USER_EMAIL=${USER_EMAIL}
      - USER_PASS=${USER_PASS}
      - USER_NICK=${USER_NICK}
    networks:
      - compose-bridge

  redis:
    container_name: redis
    build: ./redis
    expose:
      - '6379'
    restart: on-failure
    healthcheck:
      test: ['CMD', 'redis-cli','ping']
    networks:
      - compose-bridge

  ftp:
    container_name: ftp
    depends_on:
      - wordpress
    build: ./ftp
    ports:
      - '21:21'
    restart: on-failure
    volumes:
      - wordpress-data:/home/ftpuser/wordpress
    networks:
      - compose-bridge

  adminer:
    container_name: adminer
    depends_on:
      - mariadb
    build: ./adminer
    ports:
      - '4242:80'
    restart: on-failure
    networks:
      - compose-bridge

  web:
    container_name: web
    build: ./web
    ports:
      - '5000:5000'
    restart: on-failure
    networks:
      - compose-bridge

  uptime:
    container_name: uptime
    build: ./uptime
    ports:
      - '3001:3001'
    restart: on-failure
    networks:
      - compose-bridge

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '$HOME/${LOGIN_INTRA}/data/wordpress'

  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '$HOME/${LOGIN_INTRA}/data/mariadb'

networks:
  compose-bridge:
    driver: bridge
