version: '3.9'

services:
  nginx:
    build: ./nginx
    ports:
      - '3000:80'
      - '443:443'
    volumes:
      - wordpress-data:/app/wordpress
  wordpress:
    build: ./wordpress
    expose:
      - '9000'
    volumes:
      - wordpress-data:/app/wordpress

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/data/wordpress"
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "$HOME/data/mariadb"
